apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: student-a-hartl1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compdatabase
  template:
    metadata:
      labels:
        app: compdatabase
    spec:
      containers:
        - name: compdatabase
          image: postgres
          ports:
            - containerPort: 5432
              name: "postgres"
          env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              value: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: student-a-hartl1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: shared-data
          emptyDir: { }

      containers:
        - name: backend
          image: ghcr.io/2223-5ahif-nvs/03-lab-android-simple-room-db-microproject-annahartl-backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: student-a-hartl1
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: student-a-hartl1
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: compdatabase
  selector:
    app: compdatabase
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: student-a-hartl1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /student-a-hartl1/app(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
